add_rules("plugin.compile_commands.autoupdate",{outputdir="build"})
target("main")
    set_kind("binary")
    add_files("*.cpp","*.c")
    add_deps("imgui")
    add_links("spdlog","fmt","glfw")
    add_cxflags("-g","-ggdb")
    add_cxflags("-iquote./imgui")
    after_build(function (target)
        os.cp("shaders",target:targetdir())
    end)
target("imgui")
    set_kind("shared")
    add_files("imgui/*.cpp")
    add_files("imgui/backends/imgui_impl_glfw.cpp","imgui/backends/imgui_impl_opengl3.cpp")
    add_cxflags("-iquote./imgui")